
import React from 'react';
import { StudyPlan } from '../types';
import { Download, Calendar, Map, CheckCircle2, Clock, ChevronRight } from 'lucide-react';

interface PlanViewProps {
  plan: StudyPlan;
}

const PlanView: React.FC<PlanViewProps> = ({ plan }) => {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-10 animate-in fade-in zoom-in-95 duration-500">
      <div className="flex justify-between items-center no-print">
        <div>
          <h2 className="text-3xl font-bold text-gray-900 dark:text-white">Your Master Plan 🗺️</h2>
          <p className="text-gray-500">Lumina AI has processed your syllabus and created this roadmap.</p>
        </div>
        <button 
          onClick={handlePrint}
          className="bg-white dark:bg-slate-800 text-gray-700 dark:text-gray-200 px-5 py-2.5 rounded-xl font-medium flex items-center gap-2 border border-gray-200 dark:border-slate-700 hover:bg-gray-50 dark:hover:bg-slate-700 transition-all shadow-sm"
        >
          <Download className="w-4 h-4" /> Download PDF
        </button>
      </div>

      <section className="print-only hidden mb-8">
        <h1 className="text-4xl font-bold text-center mb-4">Personalized Study Plan</h1>
        <p className="text-center text-gray-600 mb-8">Generated by LuminaStudy AI</p>
      </section>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Daily Timetable */}
        <div className="lg:col-span-1 space-y-6">
          <div className="bg-white dark:bg-slate-900 rounded-3xl p-6 border border-gray-100 dark:border-slate-800 shadow-sm">
            <div className="flex items-center gap-2 mb-6 text-primary-600">
              <Clock className="w-5 h-5" />
              <h3 className="font-bold text-lg text-gray-900 dark:text-white">Daily Schedule</h3>
            </div>
            <div className="space-y-3">
              {plan.dailyTimetable.map((slot, i) => (
                <div key={i} className="flex gap-4 p-3 rounded-2xl bg-gray-50 dark:bg-slate-800/50 group hover:bg-white dark:hover:bg-slate-800 border border-transparent hover:border-primary-100 dark:hover:border-primary-900 transition-all">
                  <span className="text-xs font-bold text-primary-500 w-16 pt-1">{slot.time}</span>
                  <div>
                    <h4 className="text-sm font-semibold text-gray-900 dark:text-white group-hover:text-primary-600">{slot.activity}</h4>
                    {slot.topic && <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">{slot.topic}</p>}
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-gradient-to-br from-indigo-500 to-purple-600 rounded-3xl p-6 text-white shadow-lg shadow-indigo-500/20">
            <h3 className="font-bold text-lg mb-4">Revision Strategy</h3>
            <div className="space-y-4">
              {plan.recommendedStrategies.map((strat, i) => (
                <div key={i} className="flex gap-3 items-start">
                  <CheckCircle2 className="w-5 h-5 text-indigo-200 flex-shrink-0 mt-0.5" />
                  <p className="text-sm leading-relaxed">{strat}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Roadmap */}
        <div className="lg:col-span-2 space-y-8">
          <div className="bg-white dark:bg-slate-900 rounded-3xl p-8 border border-gray-100 dark:border-slate-800 shadow-sm">
            <div className="flex items-center gap-2 mb-8 text-indigo-600">
              <Map className="w-5 h-5" />
              <h3 className="font-bold text-xl text-gray-900 dark:text-white">Study Roadmap</h3>
            </div>
            
            <div className="relative space-y-12 before:absolute before:left-6 before:top-2 before:bottom-2 before:w-0.5 before:bg-gray-100 dark:before:bg-slate-800">
              {plan.roadmap.map((milestone, i) => (
                <div key={i} className="relative pl-14">
                  <div className="absolute left-0 top-0 w-12 h-12 bg-white dark:bg-slate-900 border-4 border-primary-500 rounded-full flex items-center justify-center z-10 shadow-sm">
                    <span className="text-sm font-black text-primary-600">{i + 1}</span>
                  </div>
                  <div className="bg-gray-50 dark:bg-slate-800/50 p-6 rounded-2xl hover:bg-gray-100 dark:hover:bg-slate-800 transition-colors border border-transparent hover:border-gray-200 dark:hover:border-slate-700">
                    <div className="flex flex-col md:flex-row md:justify-between md:items-start gap-2 mb-3">
                      <h4 className="text-lg font-bold text-gray-900 dark:text-white">{milestone.title}</h4>
                      <span className="text-xs font-bold bg-white dark:bg-slate-700 px-3 py-1 rounded-full text-gray-500 dark:text-gray-300 shadow-sm border border-gray-200 dark:border-slate-600 flex items-center gap-1">
                        <Calendar className="w-3 h-3" /> {milestone.targetDate}
                      </span>
                    </div>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">{milestone.description}</p>
                    <div className="flex flex-wrap gap-2">
                      {milestone.topics.map((topic, j) => (
                        <span key={j} className="text-xs bg-primary-100 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300 px-2 py-1 rounded-md font-medium">
                          {topic}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-white dark:bg-slate-900 rounded-3xl p-8 border border-gray-100 dark:border-slate-800 shadow-sm">
             <div className="flex items-center gap-2 mb-6 text-amber-500">
              <Calendar className="w-5 h-5" />
              <h3 className="font-bold text-lg text-gray-900 dark:text-white">Revision Checkpoints</h3>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {plan.revisionSchedule.map((rev, i) => (
                <div key={i} className="flex justify-between items-center p-4 rounded-xl border border-gray-100 dark:border-slate-800 bg-gray-50 dark:bg-slate-800/30">
                  <div>
                    <p className="font-bold text-gray-900 dark:text-white text-sm">{rev.topic}</p>
                    <p className="text-xs text-gray-500">Repetition Stage: {rev.repetitionStage}</p>
                  </div>
                  <div className="text-right">
                    <p className="text-xs font-bold text-primary-600 uppercase">{rev.date}</p>
                    <p className="text-[10px] text-gray-400">Scheduled</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PlanView;
